CREATE TABLE REVENUE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(75) NOT NULL,
    RECEIVE_DATE DATE NOT NULL,
    BUCKET_ID INT NOT NULL,
    USER_ACCOUNT_ID INT NOT NULL,
    VALUE FLOAT NOT NULL
);

ALTER TABLE REVENUE
    ADD CONSTRAINT FK_BUCKET_ID_REVENUE
    FOREIGN KEY (BUCKET_ID) REFERENCES BUCKET(ID);

ALTER TABLE REVENUE
    ADD CONSTRAINT FK_USER_ACCOUNT_ID_REVENUE
    FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID);