CREATE TABLE EXPENSE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(75) NOT NULL,
    CATEGORY_ID INT NOT NULL,
    BUCKET_ID INT NOT NULL,
    USER_ACCOUNT_ID INT NOT NULL,
    DUE_DATE DATE NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    VALUE FLOAT NOT NULL
);

ALTER TABLE EXPENSE
    ADD CONSTRAINT FK_CATEGORY_ID_EXPENSE
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID);

ALTER TABLE EXPENSE
    ADD CONSTRAINT FK_BUCKET_ID_EXPENSE
    FOREIGN KEY (BUCKET_ID) REFERENCES BUCKET(ID);

ALTER TABLE EXPENSE
    ADD CONSTRAINT FK_USER_ACCOUNT_ID_EXPENSE
    FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID);